---
# In Kubernetes a deployment is used to manange pods.
# For this task, you should have one deployment for the backend code execution
# API so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: playground-task4-server
  labels:
    app: playground-task4-server
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-task4-server
  template:
    metadata:
      labels:
        app: playground-task4-server
      namespace: task4
    spec:
      containers:
        - name: playground-task4-server
          image: "gcr.io/docker-208408/cmucourse/task2:v0.3"
          imagePullPolicy: Always
          ports:
          - containerPort: 6000
          resources:
            requests:
              cpu: "0.1"
---
# For this task, you should have one deployment for the frontend code execution UI
# so the number of replications can be increased / decreased independently.
#
#
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: playground-task4-ui
  labels:
    app: playground-task4-ui
# You should complete this spec field based on the deployment spec defined in:
# https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-task4-ui
  template:
    metadata:
      labels:
        app: playground-task4-ui
      namespace: task4
    spec:
      containers:
        - name: playground-task4-ui
          image: "gcr.io/docker-208408/cmucourse/task5ui:v0.1"
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: "0.1"
---
# A service is an abstraction that enables traffic to be routed from the network to a
# specific pod. This service should double as a Load Balancer.
# https://kubernetes.io/docs/concepts/services-networking/service/
#
#
# You should create a service for each deployment you have created above.
# https://v1-8.docs.kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: playground-task3-service
  labels:
    app: playground-task3-service
# Complete the service spec based on the documentation provided in:
#    https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#service-v1-core
spec:
  selector: 
    app: playground-task4-server
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: playground-task4-ui-service
  labels:
    app: playground-task4-ui-service
spec:
  selector: 
    app: playground-task4-ui
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
# For this task you will need to define autoscaling rules pers the write up
# to ensure that the backend pod does not exceed a certain cpu utilization.
#
# https://v1-8.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gcpbackendhpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: playground-task4-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
# For this task you will need to define autoscaling rules pers the write up
# to ensure that the frontend pod does not exceed a certain cpu utilization.
#
# https://v1-8.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gcpfrontendhp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: playground-task4-ui
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
